### ISSUE TITLE
doesn't build on go1.10

### ISSUE THREAD

**Issue by cryptix** [cryptoscope/ssb#18]
[libp2p/go-reuseport](https://github.com/libp2p/go-reuseport) states the requirement but I didn't see it.

```
# go.cryptoscope.co/ssb/vendor/github.com/libp2p/go-reuseport
vendor/github.com/libp2p/go-reuseport/interface.go:33:20: undefined: net.ListenConfig
vendor/github.com/libp2p/go-reuseport/interface.go:41:2: not enough arguments to return
vendor/github.com/libp2p/go-reuseport/interface.go:48:2: not enough arguments to return
vendor/github.com/libp2p/go-reuseport/interface.go:60:10: unknown field 'Control' in struct literal of type net.Dialer
```

I'm currently leaning towards just dropping go1.10 all together.

cc @keks @PragmaticCypher do you have objections?

**Comment by keks** [comment]
SGTM 

Am 22. Mai 2019 14:27:26 MESZ schrieb Henry <notifications@github.com>:
>libp2p/go-reuseport states the requirement but I didn't see it.
>
>```
># go.cryptoscope.co/ssb/vendor/github.com/libp2p/go-reuseport
>vendor/github.com/libp2p/go-reuseport/interface.go:33:20: undefined:
>net.ListenConfig
>vendor/github.com/libp2p/go-reuseport/interface.go:41:2: not enough
>arguments to return
>vendor/github.com/libp2p/go-reuseport/interface.go:48:2: not enough
>arguments to return
>vendor/github.com/libp2p/go-reuseport/interface.go:60:10: unknown field
>'Control' in struct literal of type net.Dialer
>```
>
>I'm currently leaning towards just dropping go1.10 all together.
>
>cc @keks @PragmaticCypher do you have objections?

-- 
Sent from mobile.

**Comment by PragmaticCypher** [comment]
Sounds good to me too :+1:

**Comment by PragmaticCypher** [comment]
Sorry it took so long for a response on this one, thought I'd replied earlier.
